from typing import TypedDict, Annotated, List, Optional
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

class AgentState(TypedDict):
    """
    The state of our multi-agent graph. This acts as the shared memory 
    passed between all nodes (agents).
    """
    # 'messages' will hold the conversation history. 
    messages: Annotated[list[BaseMessage], add_messages]
    
    # The name of the next node to execute, determined by the Supervisor.
    next_node: str
    
    # The database schema, fetched by the Schema Agent.
    schema: str
    
    # The SQL query generated by the SQL Generator Agent.
    sql_query: str
    
    # A list of validation errors, if the SQL Validator finds the query unsafe/invalid.
    sql_errors: List[str]
    
    # The raw string results returned from the database by the Executor Agent.
    raw_results: str
    
    # Flag or path to visualization output generated by the Python Agent.
    visualization_path: Optional[str]
